### ISSUE TITLE
Please support a single file as input

### ISSUE THREAD

**Issue by sschuberth** [boyter/lc#6]
As a follow-up to #5, please actually do allow a single file as input 😉

**Comment by boyter** [comment]
Hahahaha I was waiting for this one :)

Something to add once I get the release stable :)

**Comment by sschuberth** [comment]
Hehe 😆 As an extension of this, actually allowing *multiple* arguments that could be either files or directories would also be nice.

**Comment by boyter** [comment]
That's not a bad idea at all.

**Comment by boyter** [comment]
Resolved.

https://github.com/boyter/lc/releases/tag/v1.1.0

New release pushed out, and since its new functionality bumped the version to 1.1.0. Was going to update oss-review-toolkit for you with a pull request but not sure what's required there with regards to it. Looking forward to seeing the PR for it though.
